### ISSUE TITLE
Native Calendars

### ISSUE THREAD

**Issue by perpi** [traprajith/open-school-CE#2]
- In most islamic countries such as UAE, Qatar, Iran, Iraq and others, [georgian calendar](en.wikipedia.org/wiki/Gregorian_calendar) is not in use. People use [lunar/solar calendar](en.wikipedia.org/wiki/Islamic_calendar).
- People in China have their own calendar: http://en.wikipedia.org/wiki/Chinese_calendar

Anyway, is there any solution to use O-school under a native calendar?

**Comment by traprajith** [comment]
Yes we can customize as you need.

Thanks & Regards
Rajith Ramachandran*, *
Project Manager,
WIWO Enterprises Pvt. Ltd.
| Mobile: 919995504508

**Comment by traprajith** [comment]
Try latest version now.
