### ISSUE TITLE
Error Installation

### ISSUE THREAD

**Issue by dinguedelle** [traprajith/open-school-CE#3]
When i try to install, i have this message in step3,
"Fatal error: Maximum execution time of 1200 seconds exceeded in /Applications/XAMPP/xamppfiles/htdocs/open-school/protected/modules/Install/controllers/DefaultController.php on line 236"

**Comment by traprajith** [comment]
HI dinguedelle,

Please increase your max_execution_time in php.ini to 3000 or above, need more time to generate the db.

**Comment by romileee** [comment]
Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\open\core\db\CDbCommand.php on line 316

**Comment by traprajith** [comment]
Please increase your max_execution_time in php.ini to 3000 or above, need more time to generate the db.

After that remove all the files and db, then start with new copy..

**Comment by newtonmunene99** [comment]
I encountered the same error,changed timeout to 3000 and still got the same issue. So i Increased to 9000 and now its been running for almost two hours.

**Comment by traprajith** [comment]
Try latest version now.
