### ISSUE TITLE
Error In Installation

### ISSUE THREAD

**Issue by kapilupadhyay** [traprajith/open-school-CE#5]
Fatal error: Uncaught ArgumentCountError: Too few arguments to function CMap::mergeArray(), 1 passed in C:\xampp\htdocs\open-school-CE-master\protected\config\common.php on line 5 and exactly 2 expected in C:\xampp\htdocs\open-school-CE-master\core\collections\CMap.php:275 Stack trace: #0 C:\xampp\htdocs\open-school-CE-master\protected\config\common.php(5): CMap::mergeArray(Array) #1 C:\xampp\htdocs\open-school-CE-master\core\base\CApplication.php(123): require('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\open-school-CE-master\core\YiiBase.php(128): CApplication->__construct('C:\\xampp\\htdocs...') #3 C:\xampp\htdocs\open-school-CE-master\core\YiiBase.php(100): YiiBase::createApplication('CWebApplication', 'C:\\xampp\\htdocs...') #4 C:\xampp\htdocs\open-school-CE-master\index.php(51): YiiBase::createWebApplication('C:\\xampp\\htdocs...') #5 {main} thrown in C:\xampp\htdocs\open-school-CE-master\core\collections\CMap.php on line 275

**Comment by dalifig** [comment]
same error here!
did you find a solution to it?

**Comment by traprajith** [comment]
Please download the latest version.

Thanks & Regards
Rajith Ramachandran*, *
Project Manager,
WIWO Enterprises Pvt. Ltd.
| Mobile: 919995504508

**Comment by dalifig** [comment]
i alreday downloaded the last one

**Comment by traprajith** [comment]
Can you remove the environment.php file under config folder?

Thanks & Regards
Rajith Ramachandran*, *
Project Manager,
WIWO Enterprises Pvt. Ltd.
| Mobile: 919995504508

**Comment by kapilupadhyay** [comment]
Please share the latest code with database

**Comment by angeldeleon1** [comment]
I have the same problem, I deleted everything and I went back to my host and the same, and change permissions.

**Comment by traprajith** [comment]
I will update the latest version Next Week.

Rajith Ramachandran,
Executive Director | Chief Technology Officer | Project Manager,
Wiwo Enterprises Pvt. Ltd. www.wiwo.in <http://wiwo.in/index.html>  |
rajith@wiwoinc.com <mgk@wiwoinc.com>
B3 Pais Avenue, Water Land Road, Elamkulam, Kochi.
Mobile Number: +919995504508

**Comment by traprajith** [comment]
Try latest version now.
