### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by bengreat** [traprajith/open-school-CE#6]
CDbException
CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1022 Can't write; duplicate key in table '#sql-1928_2de'. The SQL statement executed was: 

-- Constraints for dumped tables
-- Constraints for table `authassignment`
--
ALTER TABLE `authassignment`
ADD CONSTRAINT `authassignment_ibfk_1` FOREIGN KEY (`itemname`) REFERENCES `authitem` (`name`) ON DELETE CASCADE ON UPDATE CASCADE

#0 | –  C:\wamp64\www\open-school\protected\modules\Install\controllers\DefaultController.php(222): CDbCommand->execute()217                 //create db schema 218                 $sql = $this->getSql($this->module->structuresPath); 219                 $sqlArr =  $this->splitQueries($sql); 220                 foreach ($sqlArr as $script) { 221                     if (preg_match('/(CREATE\s+TABLE\|DROP\s+TABLE\|ALTER\s+TABLE\|CREATE\s+VIEW\|DROP\s+VIEW)/i', $script)) 222                         $result = $connection->createCommand($script)->execute(); 223                 } 224                  225                 //insert example data 226                 $dataPath = $this->module->dataPath; 227                 if (isset($_POST['example']) === true) {
-- | --

**Comment by traprajith** [comment]
Please delete the entire db and start new installation.

Thanks & Regards
Rajith Ramachandran*, *
Project Manager,
WIWO Enterprises Pvt. Ltd.
| Mobile: 919995504508

**Comment by traprajith** [comment]
Try latest version now.
